# Generated by Django 2.2.2 on 2019-07-23 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190723_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 2, 17, 39, 794245, tzinfo=utc)),
        ),
    ]
